spring:
  kafka:
    # Adresa broker-ului Kafka
    bootstrap-servers: localhost:9092

    # Configurare Producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # Garantează că mesajele sunt primite de toți replica
      acks: all
      # Retry în caz de eroare
      retries: 3
      properties:
        spring.json.add.type.headers: false

    # Configurare Consumer
    consumer:
      group-id: my-app-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # Citește de la început dacă nu există offset salvat
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

# Topic-uri personalizate
app:
  kafka:
    topics:
      products: products-topic
      notifications: notifications-topic


springdoc:

  # Calea pentru interfața grafică Swagger UI
  # Accesibilă implicit la: http://localhost:8080/swagger-ui/index.html
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    # Sortează metodele HTTP (get, post, etc.) alfabetic
    operations-sorter: alpha

  # Calea pentru specificația JSON a API-ului
  # Accesibilă la: http://localhost:8080/v3/api-docs
  api-docs:
    path: /v3/api-docs
    enabled: true
server:
  port: 8088